config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'chatroom#index'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  post 'message', to: 'messages#create'

  resources :users , only: [:new, :create]

  mount ActionCable.server, at: '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  validates :body, presence: true
  scope :custom_display, ->  {order(:created_at).last(20) }
  
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, presence: true, length: { minimum: 3, maximum: 25 } , uniqueness: { case_sensitive: false }
  has_secure_password
  has_many :messages

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user , :logged_in?
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:error] = "You must be logged in to perform that action"
      redirect_to login_path
    end
  end

end

app/controllers/chatroom_controller.rb
class ChatroomController < ApplicationController
  before_action :require_user
  def index 
    @message = Message.new
    @messages = Message.custom_display
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :require_user

  def create 
    message = current_user.messages.build(message_params)
    if message.save
      ActionCable.server.broadcast "chatroom_channel", my_message: message_render(message)
    end
  end

  private

  def message_params
    params.require(:message).permit(:body)
  end

  def message_render (message)
    render(partial: 'message', locals: {message: message })
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :logged_in_redirect, only: [:new, :create]
  def new 
    
  end

  def create 
    user = User.find_by(username: params[:session][:username])
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id  
      flash[:success] =" Logged in successfully"
      redirect_to root_path   
    else
      flash.now[:error] = "Invalid username or password "    
      render 'new'          
    end
  end

  def destroy
    session[:user_id] = nil 
    flash[:success] =" Logged out successfully"
    redirect_to login_path
  end

  private 

  def logged_in_redirect
    if logged_in?
      flash[:error] = "You already logged in "
      redirect_to root_path
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "Welcome to the bog #{@user.username} , you are successfully signed up"
      redirect_to root_path
    else
      if User.find_by(username: @user.username)
        flash[:error] = "Username is already taken"
      elsif @user.username.length < 3 
        flash[:error] = "Username cant be less than 3 characters"
      elsif @user.password == nil 
        flash[:error] = "Password can't be blank"
      end
      render 'new'
    end
  end


  private

  def set_user
    @user = User.find(params[:id])
  end


  def user_params
    params.require(:user).permit(:username, :email, :password) 
  end

  def require_same_user 
    if current_user != @user && !current_user.admin?
      flash[:alert] = "You can only edit or delete your own account"
      redirect_to @user
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/chatroom/index.html.erb
<h1 class="ui center aligned  icon header">
  <i class="circular orange coffee icon"></i>
  Lets chat
</h1>
<div class="ui two column grid">
  <div class="ui twelve wide column">
    <div class="ui fluid raised card chatbox">
      <div class="content" id="messages">
        <div class="ui feed" id="message-contianer">
          <%= render @messages %>
        </div>
      </div>

      <div class="extra content">
        <%= form_for(@message, html: {class: "ui reply form", role: "form", remote: true }, url: message_path) do |f| %>
          <div class="field">
            <div class="ui fluid icon input">
              <%= f.text_field :body,  placeholder: "Enter a message..."%>
             <%= f.button '<i class="bordered inverted orange edit icon"></i>'.html_safe %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <div class="ui four wide column">
    <div class="ui fluid raised card chatbox">
      <div class="content">
    
      <div class="ui inverted vertical menu">
      <a class="active item">
          Home
      </a>
      <a class="item">
          Messages
      </a>
      <a class="item">
          Friends
      </a>
      </div>
      </div>
    </div>
  </div>  
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |message_type, message_content| %>
  <div class="ui <%= message_type %> message transition">
    <i class="close icon"></i>
    <div class="header">
      <%= message_content %>
    </div>
  </div>
  
<% end %>

app/views/layouts/_navigation.html.erb
<%= link_to "Chatroom" , root_path, class: "item"%>
<div class="right menu">
  <% if logged_in? %>
    <div class="item">
       <%= link_to "Log out" , logout_path, class: "ui primary button", method: :delete, data: "Are you sure"%>
    </div>
  <% else %>
    <div class="item">
       <%= link_to "Log in" , login_path, class: "ui primary button"%>
    </div>
    <div class="item">
       <%= link_to "Sign up" , new_user_path, class: "ui primary button"%>
    </div>
  <% end %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MessageMe</title>
    <%= favicon_link_tag %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="ui large inverted menu">
      <div class="ui container">
        <%= render 'layouts/navigation'%>
      </div>
    </div>
     <div class="ui container">
      <%= render 'layouts/messages'%>
      <%= yield %>
    </div>
  </body>
</html>

app/views/messages/_message.html.erb
<div class="event">
  <div class="content">
    <div class="summary">
      <em> <%= message.user.username + ":" %> </em> <%= message.body %> 
    </div>
  </div>
</div>

app/views/users/new.html.erb
<h1 class="ui center aligned header ">Welcome to MessageMe - a complete chat app </h1>
<h2 class="ui center aligned icon header">
  <i class="circular power icon  orange"></i>
  Sign up
</h2>

<div class="ui card fluid raised ">
  <div class="content">

    <%= form_with( model: @user, class: "ui form" ,  local: true) do |f| %>
      <div class="field">
        <%= f.label :username  %>
        <%= f.text_field :username , placeholder: "Enter a username "%>
      </div>
      <div class="field">
        <%= f.label :password  %>
        <%= f.password_field :password, placeholder: "Enter your password "%>
      </div>
      <%= f.submit "Sign up", class: "ui button" %>
    <% end %>

  </div>
</div>